### ISSUE TITLE
update gif demo

### ISSUE THREAD

**Issue by sipah00** [sipah00/CrickFev#17]
In the demo, use of all command is not shown.

**Comment by vchrombie** [comment]
Hello,
I am interested in this project.

So, I have to replace the gif which is present in the README.md with the new gif.

**Comment by sipah00** [comment]
@vchrombie, please change folder name assests to data and send PR.

**Comment by vchrombie** [comment]
Okay!

**Comment by vchrombie** [comment]
done :+1:

**Comment by vchrombie** [comment]
Is there anything to be done with this issue?
If not, close it.

We need to see that no one will waste their time on this issue.
