### ISSUE TITLE
lscorecard command is not working.

### ISSUE THREAD

**Issue by sipah00** [sipah00/CrickFev#2]
Running ```lscorecard``` command for any event and match, it gives error.
```AttributeError: 'NoneType' object has no attribute 'text'```

**Comment by yashrsharma44** [comment]
Is it due to change in the HTML/CSS code of espncricinfo?
Because I cannot find the `'class': 'match-information-strip'`

**Comment by yashrsharma44** [comment]
I have modified `lscorecard.py` and it is working. Should I make a pull request now or after 1st December?

**Comment by sipah00** [comment]
@yashrsharma44, Good, you can create PR.
